// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Music.proto

package com.wkk.rpc.demo;

public final class Music {
  private Music() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SingerId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SingerId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Singer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Singer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Song_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Song_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SongList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SongList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Music.proto\"\026\n\010SingerId\022\n\n\002id\030\001 \001(\005\"\"\n" +
      "\006Singer\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"9\n\004Son" +
      "g\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\027\n\006singer\030\003 " +
      "\001(\0132\007.Singer\" \n\010SongList\022\024\n\005songs\030\001 \003(\0132" +
      "\005.Song2U\n\014MusicService\022#\n\tListSongs\022\t.Si" +
      "ngerId\032\t.SongList\"\000\022 \n\010GetSongs\022\t.Singer" +
      "Id\032\005.Song\"\0000\001B\033\n\020com.wkk.rpc.demoB\005Music" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SingerId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SingerId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SingerId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Singer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Singer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Singer_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_Song_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Song_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Song_descriptor,
        new java.lang.String[] { "Id", "Name", "Singer", });
    internal_static_SongList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SongList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SongList_descriptor,
        new java.lang.String[] { "Songs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
