// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Music.proto

package com.wkk.rpc.demo;

public interface SingerIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SingerId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();
}
