// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Music.proto

package com.wkk.rpc.demo;

/**
 * Protobuf type {@code SongList}
 */
public  final class SongList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SongList)
    SongListOrBuilder {
  // Use SongList.newBuilder() to construct.
  private SongList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SongList() {
    songs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SongList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              songs_ = new java.util.ArrayList<com.wkk.rpc.demo.Song>();
              mutable_bitField0_ |= 0x00000001;
            }
            songs_.add(
                input.readMessage(com.wkk.rpc.demo.Song.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        songs_ = java.util.Collections.unmodifiableList(songs_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wkk.rpc.demo.Music.internal_static_SongList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wkk.rpc.demo.Music.internal_static_SongList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wkk.rpc.demo.SongList.class, com.wkk.rpc.demo.SongList.Builder.class);
  }

  public static final int SONGS_FIELD_NUMBER = 1;
  private java.util.List<com.wkk.rpc.demo.Song> songs_;
  /**
   * <code>repeated .Song songs = 1;</code>
   */
  public java.util.List<com.wkk.rpc.demo.Song> getSongsList() {
    return songs_;
  }
  /**
   * <code>repeated .Song songs = 1;</code>
   */
  public java.util.List<? extends com.wkk.rpc.demo.SongOrBuilder> 
      getSongsOrBuilderList() {
    return songs_;
  }
  /**
   * <code>repeated .Song songs = 1;</code>
   */
  public int getSongsCount() {
    return songs_.size();
  }
  /**
   * <code>repeated .Song songs = 1;</code>
   */
  public com.wkk.rpc.demo.Song getSongs(int index) {
    return songs_.get(index);
  }
  /**
   * <code>repeated .Song songs = 1;</code>
   */
  public com.wkk.rpc.demo.SongOrBuilder getSongsOrBuilder(
      int index) {
    return songs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < songs_.size(); i++) {
      output.writeMessage(1, songs_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < songs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, songs_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wkk.rpc.demo.SongList)) {
      return super.equals(obj);
    }
    com.wkk.rpc.demo.SongList other = (com.wkk.rpc.demo.SongList) obj;

    boolean result = true;
    result = result && getSongsList()
        .equals(other.getSongsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getSongsCount() > 0) {
      hash = (37 * hash) + SONGS_FIELD_NUMBER;
      hash = (53 * hash) + getSongsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wkk.rpc.demo.SongList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wkk.rpc.demo.SongList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wkk.rpc.demo.SongList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wkk.rpc.demo.SongList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wkk.rpc.demo.SongList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wkk.rpc.demo.SongList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wkk.rpc.demo.SongList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wkk.rpc.demo.SongList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wkk.rpc.demo.SongList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wkk.rpc.demo.SongList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wkk.rpc.demo.SongList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SongList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SongList)
      com.wkk.rpc.demo.SongListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wkk.rpc.demo.Music.internal_static_SongList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wkk.rpc.demo.Music.internal_static_SongList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wkk.rpc.demo.SongList.class, com.wkk.rpc.demo.SongList.Builder.class);
    }

    // Construct using com.wkk.rpc.demo.SongList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSongsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (songsBuilder_ == null) {
        songs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        songsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wkk.rpc.demo.Music.internal_static_SongList_descriptor;
    }

    public com.wkk.rpc.demo.SongList getDefaultInstanceForType() {
      return com.wkk.rpc.demo.SongList.getDefaultInstance();
    }

    public com.wkk.rpc.demo.SongList build() {
      com.wkk.rpc.demo.SongList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.wkk.rpc.demo.SongList buildPartial() {
      com.wkk.rpc.demo.SongList result = new com.wkk.rpc.demo.SongList(this);
      int from_bitField0_ = bitField0_;
      if (songsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          songs_ = java.util.Collections.unmodifiableList(songs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.songs_ = songs_;
      } else {
        result.songs_ = songsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wkk.rpc.demo.SongList) {
        return mergeFrom((com.wkk.rpc.demo.SongList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wkk.rpc.demo.SongList other) {
      if (other == com.wkk.rpc.demo.SongList.getDefaultInstance()) return this;
      if (songsBuilder_ == null) {
        if (!other.songs_.isEmpty()) {
          if (songs_.isEmpty()) {
            songs_ = other.songs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSongsIsMutable();
            songs_.addAll(other.songs_);
          }
          onChanged();
        }
      } else {
        if (!other.songs_.isEmpty()) {
          if (songsBuilder_.isEmpty()) {
            songsBuilder_.dispose();
            songsBuilder_ = null;
            songs_ = other.songs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            songsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSongsFieldBuilder() : null;
          } else {
            songsBuilder_.addAllMessages(other.songs_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wkk.rpc.demo.SongList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wkk.rpc.demo.SongList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.wkk.rpc.demo.Song> songs_ =
      java.util.Collections.emptyList();
    private void ensureSongsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        songs_ = new java.util.ArrayList<com.wkk.rpc.demo.Song>(songs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wkk.rpc.demo.Song, com.wkk.rpc.demo.Song.Builder, com.wkk.rpc.demo.SongOrBuilder> songsBuilder_;

    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public java.util.List<com.wkk.rpc.demo.Song> getSongsList() {
      if (songsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(songs_);
      } else {
        return songsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public int getSongsCount() {
      if (songsBuilder_ == null) {
        return songs_.size();
      } else {
        return songsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public com.wkk.rpc.demo.Song getSongs(int index) {
      if (songsBuilder_ == null) {
        return songs_.get(index);
      } else {
        return songsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public Builder setSongs(
        int index, com.wkk.rpc.demo.Song value) {
      if (songsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSongsIsMutable();
        songs_.set(index, value);
        onChanged();
      } else {
        songsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public Builder setSongs(
        int index, com.wkk.rpc.demo.Song.Builder builderForValue) {
      if (songsBuilder_ == null) {
        ensureSongsIsMutable();
        songs_.set(index, builderForValue.build());
        onChanged();
      } else {
        songsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public Builder addSongs(com.wkk.rpc.demo.Song value) {
      if (songsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSongsIsMutable();
        songs_.add(value);
        onChanged();
      } else {
        songsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public Builder addSongs(
        int index, com.wkk.rpc.demo.Song value) {
      if (songsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSongsIsMutable();
        songs_.add(index, value);
        onChanged();
      } else {
        songsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public Builder addSongs(
        com.wkk.rpc.demo.Song.Builder builderForValue) {
      if (songsBuilder_ == null) {
        ensureSongsIsMutable();
        songs_.add(builderForValue.build());
        onChanged();
      } else {
        songsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public Builder addSongs(
        int index, com.wkk.rpc.demo.Song.Builder builderForValue) {
      if (songsBuilder_ == null) {
        ensureSongsIsMutable();
        songs_.add(index, builderForValue.build());
        onChanged();
      } else {
        songsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public Builder addAllSongs(
        java.lang.Iterable<? extends com.wkk.rpc.demo.Song> values) {
      if (songsBuilder_ == null) {
        ensureSongsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, songs_);
        onChanged();
      } else {
        songsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public Builder clearSongs() {
      if (songsBuilder_ == null) {
        songs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        songsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public Builder removeSongs(int index) {
      if (songsBuilder_ == null) {
        ensureSongsIsMutable();
        songs_.remove(index);
        onChanged();
      } else {
        songsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public com.wkk.rpc.demo.Song.Builder getSongsBuilder(
        int index) {
      return getSongsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public com.wkk.rpc.demo.SongOrBuilder getSongsOrBuilder(
        int index) {
      if (songsBuilder_ == null) {
        return songs_.get(index);  } else {
        return songsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public java.util.List<? extends com.wkk.rpc.demo.SongOrBuilder> 
         getSongsOrBuilderList() {
      if (songsBuilder_ != null) {
        return songsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(songs_);
      }
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public com.wkk.rpc.demo.Song.Builder addSongsBuilder() {
      return getSongsFieldBuilder().addBuilder(
          com.wkk.rpc.demo.Song.getDefaultInstance());
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public com.wkk.rpc.demo.Song.Builder addSongsBuilder(
        int index) {
      return getSongsFieldBuilder().addBuilder(
          index, com.wkk.rpc.demo.Song.getDefaultInstance());
    }
    /**
     * <code>repeated .Song songs = 1;</code>
     */
    public java.util.List<com.wkk.rpc.demo.Song.Builder> 
         getSongsBuilderList() {
      return getSongsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wkk.rpc.demo.Song, com.wkk.rpc.demo.Song.Builder, com.wkk.rpc.demo.SongOrBuilder> 
        getSongsFieldBuilder() {
      if (songsBuilder_ == null) {
        songsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.wkk.rpc.demo.Song, com.wkk.rpc.demo.Song.Builder, com.wkk.rpc.demo.SongOrBuilder>(
                songs_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        songs_ = null;
      }
      return songsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:SongList)
  }

  // @@protoc_insertion_point(class_scope:SongList)
  private static final com.wkk.rpc.demo.SongList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wkk.rpc.demo.SongList();
  }

  public static com.wkk.rpc.demo.SongList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SongList>
      PARSER = new com.google.protobuf.AbstractParser<SongList>() {
    public SongList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SongList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SongList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SongList> getParserForType() {
    return PARSER;
  }

  public com.wkk.rpc.demo.SongList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

