// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Music.proto

package com.wkk.rpc.demo;

/**
 * Protobuf type {@code Song}
 */
public  final class Song extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Song)
    SongOrBuilder {
  // Use Song.newBuilder() to construct.
  private Song(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Song() {
    id_ = 0;
    name_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Song(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            com.wkk.rpc.demo.Singer.Builder subBuilder = null;
            if (singer_ != null) {
              subBuilder = singer_.toBuilder();
            }
            singer_ = input.readMessage(com.wkk.rpc.demo.Singer.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(singer_);
              singer_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wkk.rpc.demo.Music.internal_static_Song_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wkk.rpc.demo.Music.internal_static_Song_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wkk.rpc.demo.Song.class, com.wkk.rpc.demo.Song.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SINGER_FIELD_NUMBER = 3;
  private com.wkk.rpc.demo.Singer singer_;
  /**
   * <code>optional .Singer singer = 3;</code>
   */
  public boolean hasSinger() {
    return singer_ != null;
  }
  /**
   * <code>optional .Singer singer = 3;</code>
   */
  public com.wkk.rpc.demo.Singer getSinger() {
    return singer_ == null ? com.wkk.rpc.demo.Singer.getDefaultInstance() : singer_;
  }
  /**
   * <code>optional .Singer singer = 3;</code>
   */
  public com.wkk.rpc.demo.SingerOrBuilder getSingerOrBuilder() {
    return getSinger();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (singer_ != null) {
      output.writeMessage(3, getSinger());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (singer_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSinger());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wkk.rpc.demo.Song)) {
      return super.equals(obj);
    }
    com.wkk.rpc.demo.Song other = (com.wkk.rpc.demo.Song) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && (hasSinger() == other.hasSinger());
    if (hasSinger()) {
      result = result && getSinger()
          .equals(other.getSinger());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasSinger()) {
      hash = (37 * hash) + SINGER_FIELD_NUMBER;
      hash = (53 * hash) + getSinger().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wkk.rpc.demo.Song parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wkk.rpc.demo.Song parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wkk.rpc.demo.Song parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wkk.rpc.demo.Song parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wkk.rpc.demo.Song parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wkk.rpc.demo.Song parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wkk.rpc.demo.Song parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wkk.rpc.demo.Song parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wkk.rpc.demo.Song parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wkk.rpc.demo.Song parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wkk.rpc.demo.Song prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Song}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Song)
      com.wkk.rpc.demo.SongOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wkk.rpc.demo.Music.internal_static_Song_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wkk.rpc.demo.Music.internal_static_Song_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wkk.rpc.demo.Song.class, com.wkk.rpc.demo.Song.Builder.class);
    }

    // Construct using com.wkk.rpc.demo.Song.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      name_ = "";

      if (singerBuilder_ == null) {
        singer_ = null;
      } else {
        singer_ = null;
        singerBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wkk.rpc.demo.Music.internal_static_Song_descriptor;
    }

    public com.wkk.rpc.demo.Song getDefaultInstanceForType() {
      return com.wkk.rpc.demo.Song.getDefaultInstance();
    }

    public com.wkk.rpc.demo.Song build() {
      com.wkk.rpc.demo.Song result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.wkk.rpc.demo.Song buildPartial() {
      com.wkk.rpc.demo.Song result = new com.wkk.rpc.demo.Song(this);
      result.id_ = id_;
      result.name_ = name_;
      if (singerBuilder_ == null) {
        result.singer_ = singer_;
      } else {
        result.singer_ = singerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wkk.rpc.demo.Song) {
        return mergeFrom((com.wkk.rpc.demo.Song)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wkk.rpc.demo.Song other) {
      if (other == com.wkk.rpc.demo.Song.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasSinger()) {
        mergeSinger(other.getSinger());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wkk.rpc.demo.Song parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wkk.rpc.demo.Song) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private com.wkk.rpc.demo.Singer singer_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wkk.rpc.demo.Singer, com.wkk.rpc.demo.Singer.Builder, com.wkk.rpc.demo.SingerOrBuilder> singerBuilder_;
    /**
     * <code>optional .Singer singer = 3;</code>
     */
    public boolean hasSinger() {
      return singerBuilder_ != null || singer_ != null;
    }
    /**
     * <code>optional .Singer singer = 3;</code>
     */
    public com.wkk.rpc.demo.Singer getSinger() {
      if (singerBuilder_ == null) {
        return singer_ == null ? com.wkk.rpc.demo.Singer.getDefaultInstance() : singer_;
      } else {
        return singerBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Singer singer = 3;</code>
     */
    public Builder setSinger(com.wkk.rpc.demo.Singer value) {
      if (singerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        singer_ = value;
        onChanged();
      } else {
        singerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .Singer singer = 3;</code>
     */
    public Builder setSinger(
        com.wkk.rpc.demo.Singer.Builder builderForValue) {
      if (singerBuilder_ == null) {
        singer_ = builderForValue.build();
        onChanged();
      } else {
        singerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .Singer singer = 3;</code>
     */
    public Builder mergeSinger(com.wkk.rpc.demo.Singer value) {
      if (singerBuilder_ == null) {
        if (singer_ != null) {
          singer_ =
            com.wkk.rpc.demo.Singer.newBuilder(singer_).mergeFrom(value).buildPartial();
        } else {
          singer_ = value;
        }
        onChanged();
      } else {
        singerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .Singer singer = 3;</code>
     */
    public Builder clearSinger() {
      if (singerBuilder_ == null) {
        singer_ = null;
        onChanged();
      } else {
        singer_ = null;
        singerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .Singer singer = 3;</code>
     */
    public com.wkk.rpc.demo.Singer.Builder getSingerBuilder() {
      
      onChanged();
      return getSingerFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Singer singer = 3;</code>
     */
    public com.wkk.rpc.demo.SingerOrBuilder getSingerOrBuilder() {
      if (singerBuilder_ != null) {
        return singerBuilder_.getMessageOrBuilder();
      } else {
        return singer_ == null ?
            com.wkk.rpc.demo.Singer.getDefaultInstance() : singer_;
      }
    }
    /**
     * <code>optional .Singer singer = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wkk.rpc.demo.Singer, com.wkk.rpc.demo.Singer.Builder, com.wkk.rpc.demo.SingerOrBuilder> 
        getSingerFieldBuilder() {
      if (singerBuilder_ == null) {
        singerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.wkk.rpc.demo.Singer, com.wkk.rpc.demo.Singer.Builder, com.wkk.rpc.demo.SingerOrBuilder>(
                getSinger(),
                getParentForChildren(),
                isClean());
        singer_ = null;
      }
      return singerBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Song)
  }

  // @@protoc_insertion_point(class_scope:Song)
  private static final com.wkk.rpc.demo.Song DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wkk.rpc.demo.Song();
  }

  public static com.wkk.rpc.demo.Song getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Song>
      PARSER = new com.google.protobuf.AbstractParser<Song>() {
    public Song parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Song(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Song> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Song> getParserForType() {
    return PARSER;
  }

  public com.wkk.rpc.demo.Song getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

