// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Music.proto

package com.wkk.rpc.demo;

public interface SongOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Song)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional .Singer singer = 3;</code>
   */
  boolean hasSinger();
  /**
   * <code>optional .Singer singer = 3;</code>
   */
  com.wkk.rpc.demo.Singer getSinger();
  /**
   * <code>optional .Singer singer = 3;</code>
   */
  com.wkk.rpc.demo.SingerOrBuilder getSingerOrBuilder();
}
