// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package com.wkk.grpc.hello;

public interface RPCDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wkk.grpc.RPCDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string userName = 1;</code>
   */
  String getUserName();
  /**
   * <code>optional string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
